### ISSUE TITLE
No access to raw audio

### ISSUE THREAD

**Issue by jussi-kalliokoski** [soundcloud/soundcloud-javascript#1]
Currently there seems to be no way to access the raw audio sample data from JavaScript. This of course is due to CORS restrictions on the audio files.

Adding CORS headers to that data is a must to enable SoundCloud sounds to be used with the [Web Audio API](https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html), which allows people to create a whole new world of sound-based applications (e.g. an application for mastering the sound you have on SC, a game to apply ambient effects to the background music that is user-selectable from SC tracks, WebGL visualizations, etc.).

Using a proxy is an option, but not a very tempting one; if you have a lot of traffic, you're going to be proxying massive amounts of data. And what's the point of getting your sound data from SoundCloud anyway if you need to proxy it, might as well just store the stuff you need on your own server.

Seriously, I doubt that SoundCloud wants to miss this train by not adding CORS headers to the audio.

P.S. I realize that this is not the right issue tracker, but it's the closest thing I could find, seems that the "api" repo doesn't exist anymore.

**Comment by jtenner** [comment]
I really need this badly. Please add the headers! Thanks!

**Comment by mattdesl** [comment]
:+1: This is going to be more pronounced now that Chrome is doing CORS access check on `createMediaElementSource`

**Comment by luigimannoni** [comment]
Bumping this, since few weeks I am having the same exact problem mentioned above breaking most a couple of experiments I coded. 
Is there any chance to open up CORS on mp3 files or any way I can access raw data (through a proxy or something) without breaking the Soundcloud TOS?

**Comment by padenot** [comment]
This can work is you set your HTMLMediaElement `crossOrigin` attribute to "anonymous".

```javascript
var audio = document.createElement("audio");
audio.crossOrigin = "anonymous";
audio.src = "https://soundcloud.com/blablabla.mp3";
var ac = new AudioContext();
ac.createMediaElementSource(audio).connect(ac.destination);
audio.play();
```

**Comment by luigimannoni** [comment]
Works flawlessly, thank you very much!

**Comment by deanh** [comment]
Hi there. Downloading or caching audio content from the SoundCloud API is explicitly against the Terms of Use (https://developers.soundcloud.com/docs/api/terms-of-use#caching). PLEASE DON'T DO THAT!

(Will not fix).

**Comment by jtenner** [comment]
@deanh I was trying to simply cache it to reasonably play back audio in my app!

"Your app may employ session-based caching, but only to the extent reasonably necessary for the operation of your app."

**Comment by jtenner** [comment]
I'm 99% sure what I was trying to do was reasonable.
