### ISSUE TITLE
JS track properties broken in the SoundCloud API

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/soundcloud-javascript#101]
Using https://connect.soundcloud.com/sdk/sdk-3.3.2.js, something recently broke. I'm unable to write to a handful of track properties defined [here](https://developers.soundcloud.com/docs/api/reference#tracks). I've put the [issue up at StackOverflow](https://stackoverflow.com/questions/63222180/has-the-soundcloud-api-changed-how-to-write-the-release-property-on-the-tracks-e) and haven't heard anything from the dev team.

`release` and `privacy`, among other properties, are now unwritable. I've been seeing this issue for about 3 weeks regardless of the API wrapper or API key. Below is an example of not being able to write the `release` property on the `/tracks` endpoint. No error code is generated. It simply doesn't write.

```
SC.initialize({
	oauth_token: TOKEN
});

SC.put('/tracks/XXXXXXXXXX', {
	track: {
		title: "TEST TITLE",
		release: "012345"
	}
}).then(function(data) {
	console.log(data.title); // returns "TEST TITLE"
	console.log(data.release); // returns null
}).catch(function(error) {
	console.log(error);
});

```

Anyone else having this problem?

**Comment by rahul-sc** [comment]
This should be resolved now. Please confirm.

**Comment by alexweinstein** [comment]
Confirmed. This has been resolved. Thank you!
