### ISSUE TITLE
Client ID discrimination causing 404 errors on stream urls

### ISSUE THREAD

**Issue by rahilsondhi** [soundcloud/soundcloud-javascript#12]
This request to `/api/tracks/TRACK_ID/stream` fails gets a `404 Not Found`:

```
curl --head http://api.soundcloud.com/tracks/152675057/stream?client_id=986b39d4513a5b501d57d973318715f0
```

This request to the identical URL but with a different client_id gets a `302 Found` with `Location: MP3_URL`:
```
curl --head http://api.soundcloud.com/tracks/152675057/stream?client_id=0f8fdbbaa21a9bd18210986a7dc2d72c
```

To prove that the first client_id isn't bad, a request to `/api/tracks/TRACK_ID` gets a `200 Found`.

```
curl --head http://api.soundcloud.com/tracks/152675057?client_id=986b39d4513a5b501d57d973318715f0
```

I'm trying to use the SoundCloud JS SDK (connect.soundcloud.com/sdk.js) to stream music from SoundCloud but I'm getting a lot of 404s when I do `SC.stream('/tracks/TRACK_ID')`

Please advise.

**Comment by jhorvat** [comment]
Does anyone know of some way to ensure that there is an HTTP resource? Currently running into this as well with a custom player

**Comment by francismakes** [comment]
@jhorvat 

Using `curl`, hitting the `i1` endpoint with your desired `track_id` and a [registered `API_KEY`](http://soundcloud.com/you/apps/new) is the first step to checking for the actual resources on a SoundCloud hosted track. (Warning: the `i1` endpoint is not officially documented in SoundCloud's [HTTP API Reference](https://developers.soundcloud.com/docs/api/reference))

```shell
curl https://api.soundcloud.com/i1/tracks/{{track_id}}/streams?client_id={{API_KEY}}
```

This will return a JSON object that looks something like:
```json
{
    "http_mp3_128_url": "{some_url}",
    "preview_mp3_128_url": "{some_url}"
}
```

If the `http_mp3_128_url` key-value pair exists, then that track has an accessible HTTP resource.

Shout out to the @soundcloud developer who wrote the `window.console.info("You like to look under the hood? Why not help us build the engine? http://soundcloud.com/jobs")`. You encouraged me to find a solution.

**Comment by jackread** [comment]
If you switch your client_id in the requests to soundcloud's client_id... the http resources magically appear.

This is by no means a solution, just an observation.

**Comment by ummjackson** [comment]
@francismakes - is there any better workaround now? Don't like the idea of making two HTTP requests for every track...

**Comment by francismakes** [comment]
@ummjackson To my best knowledge and explorations, there is not currently a better workaround.

The `stream.coffee` source file serves as the component for loading any track. [Lines 63-66](https://github.com/soundcloud/soundcloud-javascript/blob/a1da58a8b7cf3e50dc62ee280635825777413e5d/src/sc/stream.coffee#L63-L66) run the two HTTP requests when the stream is ready. 

From SoundCloud's web app and found the two HTTP requests are initiated once I press play on a given track.

Has anyone else found different results?

**Comment by 12preschph** [comment]
@francismakes I have found the same thing to be true. Unfortunately, it looks like their documentation is lacking quite a bit.

**Comment by jeena** [comment]
Why is this closed suddenly?

**Comment by deanh** [comment]
This is not an issue with the JS SDK.

**Comment by jeena** [comment]
But we are using the js sdk as in the dokumentation and it doesn't work because we get 404's, åt least change the dokumentation to reflect that one can't use SC.stream('/tracks/TRACK_ID')

**Comment by deanh** [comment]
We just merged a PR that was a major update to the SDK. The documentation has been revised entirely and will be posted next week. Cheers.

**Comment by 7six** [comment]
Hey, Guys!

I don't know if  You've already solved that problem or not, but my code works in this way.

<//script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
 
  <//script type='text/javascript'>
    var clientId = 'client_id=your_app_code',
    secretToken = 'secret_token=your_private_token_in_each_track',
    trackUri = 'https://api.soundcloud.com/tracks/210702559.json?' + 
    secretToken + '&' + clientId;
        
	trackUri = 'https://api.soundcloud.com/i1/tracks/210702559/streams?' + secretToken + '&' + clientId;

	$.get(encodeURI(trackUri))
	  .then(function (result) {
	  	console.debug(result);
	    $('#audi').attr('src', encodeURI(result.http_mp3_128_url));
	  });
  <///script>
</head>
<body>
  <audio id="audi" controls></audio>
</body>
