### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow' when another iframe is present

### ISSUE THREAD

**Issue by camwes** [soundcloud/soundcloud-javascript#15]
I have been working with using youtube videos and soundcloud widgets on the same page in a queue. I've noticed that when transitioning from playing youtube to soundcloud widgets I consistently see this postMessage error:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://w.soundcloud.com') does not match the recipient window's origin ('http://localhost:8000).
```

**Comment by francismakes** [comment]
### Observation # 1
From [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage):
> The window.postMessage method safely enables cross-origin communication. Normally, scripts on different pages are allowed to access each other if and only if the pages that executed them are at locations with the same protocol (usually both http), port number (80 being the default for http), and host (modulo document.domain being set by both pages to the same value).

From your posted error, it seems like the window's origin is served up on `http` whereas the target origin is served up on `https`. Have you tried serving up the window origin from `https`?

### Observation # 2
The [Youtube iFrame source](https://s.ytimg.com/yts/jsbin/www-widgetapi-vfllgPgCl/www-widgetapi.js) uses `postMessage` like so:

```js
// my best attempt to parse minified code
for(c = 0; c < b.length; c++)
  try {
    this.d.contentWindow.postMessage(a, b[c])
  } catch(l) {
    if (l.name && "SyntaxError" == l.name) Ja(l,"WARNING");
    else throw l;
  }
```

Could be useful for noting what `postMessage` does in Youtube Embed versus SoundCloud embed.

### Observation # 3
* SoundCloud does note this in their [Widget API#getters](https://developers.soundcloud.com/docs/api/html5-widget#getters):

> Since communication between the parent page and the widget's iframe is implemented through window.postMessage, it's not possible to return the value synchronously. Because of this, every getter method accepts a callback function as a parameter which, when called, will be given the return value of the getter method.

This piece of information could be helpful with regard to isolating how the communication protocol flow works.

Hope you find your solution!

**Comment by camwes** [comment]
@francismakes Great observations! 
### Re: Observation #1 
I switched to https which I would have had to do anyway. Didn't solve my problem but worth doing anyway since it had to be done eventually regardless
### Re: Observation #2 
I will look into the Youtube Api as well in depth, the error occurs rarely with their APi as well
### Re: Observation #3 
I don't currently use any getters in my app, but am only using SC.Widget.Events. Do these events rely on Getters as well?

**Comment by francismakes** [comment]
@camwes I will have a look at the source code for the SC.Widget and note more obseravtions. Is it possible to replicate your problem on a jsfiddle / jsbin / online editor? I would welcome a code review / audit to figure out how things are firing back and forth in that system. Let me know dude!

**Comment by francismakes** [comment]
I noticed that the SoundCloud Widget API source code is not hosted within this repository but under `https://w.soundcloud.com/player/api.js`. I have a [beautified version of it on a gist](https://gist.github.com/francismakes/165aaee99dcc2fe70adf) so I'll be poking around that for now.

**Comment by camwes** [comment]
So I resolved this issue in my application by changing the way that I was creating widgets. Previously my code had been creating and destroying widgets on the page using dom methods (namely innerHTML); My theory is that there were race conditions from this strategy. So I rewrote the code to reuse the same widget item (attached to the window) and it is hidden/shown appropriately. If you are curious my oEmbed callback is now: 

```
    /**
     * Widget Callback
     * @param {object} oEmbed
     */
    _widgetCallback: function (seek, oEmbed) {
      if (typeof window.widget !== "undefined") {
        // No need to load and bind, reuse the widget
        window.widget.load(this.props.trackMetadata.trackToken.url, { auto_play: true, iframe: true, show_artwork: true, visual: true, liking: false, download: false }, this._soundCloudReady(seek, widget));
        return;
      }
      var container = document.getElementById('widgetContainer');
      if(container) {
        container.innerHTML = oEmbed.html;
        var iframeElement = container.childNodes[0];
        var sc            = SC.Widget(iframeElement);
        window.widget     = sc;
        window.widget.bind(SC.Widget.Events.READY, function() {
          window.widget.bind(SC.Widget.Events.PLAY_PROGRESS, this._positionChanged);
          window.widget.bind(SC.Widget.Events.FINISH, function () {
            this._soundCloudStop();
          }.bind(this));
        }.bind(this));
      }
      this._soundCloudReady(seek, widget);
    },
```

**Comment by camwes** [comment]
Thanks so much @francismakes for all of your suggestions, they were critical in understanding precisely how the widget worked.

**Comment by francismakes** [comment]
@camwes You're welcome man. I'm glad everything worked out.

Since these questions are just out of my own curiosity, feel free to answer what you're most comfortable with (no pressure, just extending the conversation). Here goes:

* Is `_widgetCallback()` only going to call once in your application context? If it happens to be called more than once and the container exists, would the three function callbacks be bound to `window.widget` again? 
* If the widget is undefined (case 1) and the container does not exist (case 2), the callback still runs `this._soundCloudReady(seek, widget)`. `seek` is scoped as a function parameter, but where would the argument `widget` be defined? I can see its assignment readily set within the if-block for a truthy container, but is it initialized and set elsewhere as a global?

**Comment by camwes** [comment]
* theoretically widgetCallback should only be called once with the callbacks bound to the widget in perpetuity.If the widget is somehow destroyed this method assumes it needs to create a new widget and perform all the necessary binding again. 
* this._soundCloudReady should not be called when there is no widget or container (good catch!) but in the context of my app that's almost guaranteed not to occur. Also widget in this situation no longer needs to be bound explicitly since I am saving the widget to the window object

**Comment by francismakes** [comment]
+1 for using the word perpetuity. I appreciate your responses! If I ever
decide to use the SoundCloud embed, I will make sure to reference this
issue for future reference.
