### ISSUE TITLE
Avoid hardcoded `window.location.protocol`

### ISSUE THREAD

**Issue by jtomaszewski** [soundcloud/soundcloud-javascript#16]
Currently in the SDK protocol is hardcoded (a lot of `window.location.protocol` references). This makes the SDK unusable in Apache Cordova - as apps there have a `file://` protocol.

A simple fix replacing all `window.location.protocol` with f.e. `SC.options.protocol` would be sufficient.

**Comment by gillesdemey** [comment]
Currently experiencing the same issue using Electron (or Node WebKit for that matter).

**Comment by angusfretwell** [comment]
:+1:

**Comment by chrisrickard** [comment]
Same issue... quite a show stopper.

Any word on this? 

:+1::+1::+1:

**Comment by gillesdemey** [comment]
I've been using my own simple module for now, but I'm happy to take a look at this and send a PR if they're being looked at (I see a few PR's open from years ago).

**Comment by bluedaniel** [comment]
Yeah seeing this as well

**Comment by angusfretwell** [comment]
Here's a patched copy of the minified API which I bundled as a node module: https://github.com/angusfretwell/soundcloud-cordova-sdk

Suppose I should remove Cordova from the name of the package since this problem isn't really specific to Cordova :sweat_smile:
