### ISSUE TITLE
Soundcloud Javascript SDK 2.0 returns 404 when downloading audiomanager.js

### ISSUE THREAD

**Issue by tijwelch** [soundcloud/soundcloud-javascript#20]
The Soundcloud Javascript SDK sends a GET request to http://connect.soundcloud.com/audiomanager/audiomanager.js. This is returning a 404 and cannot stream as a result.

This seems to be a bug on Soundcloud's side as this was working last night and no changes were made to my implementation.

Any suggestions on getting this sorted out would be appreciated.

**Comment by tijwelch** [comment]
Here's a JSFiddle showing the issue https://jsfiddle.net/xkrfd940/. The browser console shows a 404 error when downloading audio-manager.

**Comment by deanh** [comment]
Hi there. We moved hosts today and it looks like this file wasn't part of the new build. I just added it to the CDN. Let me know if you're still having issues.

**Comment by tijwelch** [comment]
Thanks. Seems to have fixed it.
