### ISSUE TITLE
soundcloud-javascript won't initialize on Node v4.1.1

### ISSUE THREAD

**Issue by ianalexander** [soundcloud/soundcloud-javascript#23]
I'm having an issue using soundcloud-javascript with the lastest version of node. Steps to reproduce below:

```shell
$ node --version
v4.1.1
$ npm --version
2.14.4
$ npm init
$ npm install --save soundcloud
$ cat index.js 
var SC = require('soundcloud');

SC.initialize({
  client_id: '~~redacted~~',
  redirect_uri: '~~redacted~~'
});

$ node index.js 
scTest/node_modules/soundcloud/sdk.js:8
(function(){"use strict";function a(t){return"function"==typeof t||"object"==typeof t&&null!==t}function u(t){return"function"==typeof t}function l(t){return"object"==typeof t&&null!==t}function c(t){$=t}function h(t){J=t}function f(){var e=t.nextTick,n=t.versions.node.match(/^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/);return Array.isArray(n)&&"0"===n[1]&&"10"===n[2]&&(e=r),function(){e(m)}}function d(){return function(){q(m)}}function p(){var t=0,e=new et(m),n=document.createTextNode("");return e.observe(n,{characterData:!0}),function(){n.data=t=++t%2}}function _(){var t=new MessageChannel;return t.port1.onmessage=m,function(){t.port2.postMessage(0)}}function g(){return function(){setTimeout(m,1)}}function m(){for(var t=0;Q>t;t+=2){var e=rt[t],n=rt[t+1];e(n),rt[t]=void 0,rt[t+1]=void 0}Q=0}function y(){try{var t=n(27);return q=t.runOnLoop||t.runOnContext,d()}catch(e){return g()}}function v(){}function A(){return new TypeError("You cannot resolve a promi

TypeError: Cannot read property 'getUserMedia' of undefined
    at Object.<anonymous> (scTest/node_modules/soundcloud/sdk.js:8:16199)
    at Object.n (scTest/node_modules/soundcloud/sdk.js:8:16329)
    at e (scTest/node_modules/soundcloud/sdk.js:1:414)
    at Object.<anonymous> (scTest/node_modules/soundcloud/sdk.js:8:16746)
    at e (scTest/node_modules/soundcloud/sdk.js:1:414)
    at Object.<anonymous> (scTest/node_modules/soundcloud/sdk.js:1:601)
    at Object.$ (scTest/node_modules/soundcloud/sdk.js:1:1411)
    at e (scTest/node_modules/soundcloud/sdk.js:1:414)
    at scTest/node_modules/soundcloud/sdk.js:1:501
    at scTest/node_modules/soundcloud/sdk.js:1:506
```

A quick glance at the source leads me to believe we're trying to call getUserMedia on a `navigator` object which is undefined (because we're in node). Offending area of code might be here: https://github.com/soundcloud/soundcloud-javascript/blob/a77aa6af2cfcfde9d310e8f1e775f65230e25750/src/recorder/getusermedia.js#L1

Please let me know if I can provide any other details!

**Comment by deanh** [comment]
Hi Ian,

Even though the SDK is available via npm, it currently still requires a browser–we use browser features for playback and upload. We'll probably look into decoupling these features into separate modules in the future, but for now you'll need to use an alternative module with Node.

**Comment by Zougi** [comment]
you should specify this on the npm package description =/

https://www.npmjs.com/package/soundcloud

**Comment by monsterkodi** [comment]
I agree with Zougi. 
I also think this issue should not have been closed.

**Comment by 0xPr0xy** [comment]
I agree with Zougi and monsterkodi.

**Comment by druvisc** [comment]
Didn't expect this.

**Comment by nicolasiensen** [comment]
I was planning to use this library on a react-native project, but unfortunately I'll have to look for another solution because of this dependency of the lib with the browser. If anybody here have suggestions for me I'll be appreciated ;)
