### ISSUE TITLE
Unable to use SC.get() with next_href pagination on activities

### ISSUE THREAD

**Issue by ehotinger** [soundcloud/soundcloud-javascript#24]
Right now, you can't use `SC.get([some next_href])` or `future_href` with activities.

It will try to append the `hostname` and mess up the json formatting.

**Comment by ArturJanik** [comment]
I second that. At least jquery $.getJSON works on them.

**Comment by janmonschke** [comment]
@ehotinger @ArturJanik You have to extract the `cursor` from the `next_href` and pass them in your subsequent calls like this:

    SC.get('me/activities', { cursor: 'EXTRACTEDCURSOR' }).then(function(ac){ console.log(ac)});
