### ISSUE TITLE
docs say redirect_uri is optional

### ISSUE THREAD

**Issue by davis** [soundcloud/soundcloud-javascript#26]
https://developers.soundcloud.com/docs/api/sdks#javascript

however, when trying to initialize without it i get this error:

`Error: Options client_id and redirect_uri must be passed`

**Comment by janmonschke** [comment]
@davis You need to specify the `redirect_uri` if you want to authenticate your requests. So if you use `SC.connect`, you also have to provide a `redirect_uri`.

The documentation mentions it as well, but maybe not strongly enough:

> (...) initialize the client with your own client_id and optionally your redirect_uri in case you want to use authentication (...)

- https://developers.soundcloud.com/docs/api/sdks#basic
