### ISSUE TITLE
SC.put does not use oauth_token

### ISSUE THREAD

**Issue by eteubert** [soundcloud/soundcloud-javascript#28]
I am using version 3.0.0 of the JavaScript SDK. I manage to connect, get tracks and upload new tracks. However, updating track metadata is not working. For example:

```js
SC.put('/tracks/231833159', {
    track: {
        title: "New Track Title"
    }
});
```

Response to the OPTIONS request:

```
Request URL: https://api.soundcloud.com/tracks/231833159?
Request Method: OPTIONS
Status Code: 401 Unauthorized
```

It seems like the SC.put call omits the parameters for format and the oauth token.

Is it a bug in the new SC API v3.0.0 or am I doing it wrong?

**Workaround**

You can manually add the oauth_token to the URL. The '&' at the end of the URL, is necessary because the API wrapper appends a '?'.

```js
SC.put('/tracks/' + track.id + '?format=json&oauth_token=' + oauth_token + '&', {
    track: {
        title: "New Track Title"
    }
});
```

Original report: https://stackoverflow.com/questions/33581675/soundcloud-updating-track-metadata-not-working

**Comment by vikcheema** [comment]
I am also getting the error "NetworkError: 401 Unauthorized - https://api.soundcloud.com/me/followings/******89472?"
while using the SC.put('me/followings/***1234');
