### ISSUE TITLE
Publish version 3.0.1 on SC.com

### ISSUE THREAD

**Issue by JorritPosthuma** [soundcloud/soundcloud-javascript#30]
Hi!

`https://connect.soundcloud.com/sdk/sdk-3.0.0.js` works, however, `https://connect.soundcloud.com/sdk/sdk-3.0.1.js` (which fixes the flash bug) doesn't :cry: 

Self hosting isn't a problem, but it would be nice for others.

**Comment by janmonschke** [comment]
@JorritPosthuma we will upload the new SDK soon. For now, you can get it via NPM: https://www.npmjs.com/package/soundcloud

**Comment by nickoneill** [comment]
How about now? I'm having issues with `make build` straight from npm so I can't get a version the flash bug fixed otherwise.

**Comment by salomvary** [comment]
We just published `https://connect.soundcloud.com/sdk/sdk-3.1.1.js`
