### ISSUE TITLE
Callback window didn't work

### ISSUE THREAD

**Issue by Lexicality** [soundcloud/soundcloud-javascript#33]
I'm using FireFox 43 and the callback.html with
`<body onload="window.opener.setTimeout(window.opener.SC.connectCallback, 1)">`
hung for me.
It worked when I changed it to 
`<body onload="window.opener.SC.connectCallback.call(window)">`
which is also smaller.
I'd send a pull request, but the callback file doesn't seem to be documented in this repository (?)

**Comment by oswaldoferreira** [comment]
Also had problems with this line on Chrome (Version 47.0.2526.106 - 64-bit). It worked well with this tiny change.

**Comment by janmonschke** [comment]
Sorry, we forgot to update that part of the documentation. The change should be live soon.

There is however an example of a working `callback.html` in this repositories [examples folder](https://github.com/soundcloud/soundcloud-javascript/blob/master/examples).

**Comment by neopostmodern** [comment]
I just wanted to bump this. The documentation isn't updated, yet it's hard to find this bug because it's marked as closed.

**Comment by janmonschke** [comment]
@neopostmodern Did you check if it works for you with the `callback.html` that is used in this project's example folder? https://github.com/soundcloud/soundcloud-javascript/blob/master/examples/callback.html

**Comment by neopostmodern** [comment]
Yes, that works. I was only referring to the fact that it's hard to find the right solution.
Is there any upgrade guide? (2.x > 3.x)

**Comment by janmonschke** [comment]
@neopostmodern @oswaldoferreira @Lexicality The documentation has been updated now, thx for reporting!
