### ISSUE TITLE
Can't play sound in Safari OSX - Issue with latest fix

### ISSUE THREAD

**Issue by andratwiro** [soundcloud/soundcloud-javascript#70]
Hey @diurnalist, I tried the fix you published on #27, but I keep getting the same error on my page ([viberaid.com](http://www.viberaid.com)):

`XMLHttpRequest cannot load https://api.soundcloud.com/tracks/213984415.json?client_id=55c6772672dd77c1147fc334e0d5ed83. Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.`

`Failed to load resource: Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.`

**Comment by errazib** [comment]
+1

**Comment by andratwiro** [comment]
It was an error on my part. I refactored my code from 

`SC.get("")`

to

`SC.resolve("")`

and it works perfectly!! :) My full code to get a working stream (plus title) is:

```
var clientID = "your client ID"
var SCurl = "soundcloud URL you wanna stream"
var request = SC.resolve(SCurl).then(function(result){
        var data = JSON.stringify(result);
        var json = JSON.parse(data);
        var streamMP3 = json["stream_url"];
        var streamTitle = json["title"];
        var streamMP3auth = streamMP3 + '?client_id=' + clientID;
});
```

Then you just serve streamMP3auth and streamTitle to a player (I use jPlayer) and voilá.

**Comment by diurnalist** [comment]
@andratwiro that's great! Sorry I didn't get back to you before. Glad it was fixed up in the SDK. I'll close this for now then :)
