### ISSUE TITLE
SDK.js is 404.

### ISSUE THREAD

**Issue by lljb3** [soundcloud/soundcloud-javascript#73]
Hey, thought you guys should know, unless you're getting rid of the Soundcloud API and JavaScript SDK, the sdk.js file is throwing out a 404 (assuming it has been deleted by accident). Any thoughts on when this will be up again?

**Comment by super-kamil** [comment]
+1

**Comment by alexweinstein** [comment]
Does anyone have a local backup?

**Comment by alexweinstein** [comment]
+1

On Tue, Sep 6, 2016 at 2:11 PM, Kamil Kubica <notifications@github.com> wrote:
+1

**Comment by diurnalist** [comment]
Just to update here: yes, we had an issue with our connect.soundcloud.com at this time. I believe it lasted a few hours. The domain was restored soon after the error was detected. Thanks for the report :)
